const asset = (name: string, ext = "png") => `/figma-assets/${name}.${ext}`;

export const imgRectangle3 = asset("bg-column");
export const imgEllipse1 = asset("glow-left", "svg");
export const imgEllipse2 = asset("glow-bottom", "svg");
export const imgEllipse3 = asset("glow-right", "svg");
export const imgEllipse4 = asset("glow-top-right", "svg");
export const imgImage1 = asset("profile");
export const imgImage2 = asset("project-netflix");
export const imgImage3 = asset("project-gearx");
export const imgImage4 = asset("project-mobile");
export const imgImage5 = asset("project-ecommerce");
export const imgPolygon = asset("scroll-marker", "svg");
export const imgEllipseReact = asset("tech-react", "svg");
export const imgEllipseTS = asset("tech-ts", "svg");
export const imgEllipseVite = asset("tech-vite", "svg");
export const imgEllipseJS = asset("tech-js", "svg");
export const imgEllipseCSS = asset("tech-css", "svg");
export const imgEllipseNode = asset("tech-node", "svg");
export const imgEllipsePostgres = asset("tech-postgres", "svg");
export const imgEllipseDocker = asset("tech-docker", "svg");
export const imgEllipseAWS = asset("tech-aws", "svg");
export const imgJava = asset("java-icon", "svg");
export const imgVector = asset("corner-vector", "svg");
